FROM golang:1.22-alpine
# RUN apk update && apk add --no-cache ca-certificates # If your app calls out to the internet

WORKDIR /app

COPY go.mod go.sum ./

RUN go mod download

COPY . .

RUN go install github.com/cosmtrek/air@latest

CMD ["air", "--build.cmd", "go build -o .temp/main ./main.go", "--build.bin", "./.temp/main"]